### PR TITLE
Rework security groups and rules

### PR DESCRIPTION
**Pull request by nekwar**
- According to official MKE docs (https://docs.mirantis.com/mke/3.7/install/predeployment/configure-networking/open-ports.html)
- ALSO Add dependency between vnet and manager modules

### CODE REVIEW

**Review by dimitarbytes — CHANGES_REQUESTED** [review]
Can you add a couple more ports. We have a ticket: https://mirantis.jira.com/browse/PRODENG-2376 
According to the latest MKE docs it needs 12376 - 12392 ports open

**Comment by nekwar** [comment]
@cranzy got it, thank you. Let me get some more details and then I'll update SG list. BTW -- I've tested it and it seems to be working fine

**Comment by nekwar** [comment]
@cranzy @james-nesbitt do you think we need to include all those ports? Here is the Dmitrii's reply on how those ports are used: https://mirantis.jira.com/browse/PRODENG-2376?focusedCommentId=1029953. He stated that it is primarily for testing purposes...

**Comment by dimitarbytes** [comment]
> @cranzy @james-nesbitt do you think we need to include all those ports? Here is the Dmitrii's reply on how those ports are used: https://mirantis.jira.com/browse/PRODENG-2376?focusedCommentId=1029953. He stated that it is primarily for testing purposes...

I mean, the only scenario I can think of is: If Testing team or some other kind of testing moves onto testing with the OpenStack provider.

My opinion is to include all ports

**Review by dimitarbytes — APPROVED** [review]

**Pull request merged**
